### ISSUE TITLE
Website / whitelists etc.

### ISSUE THREAD

**Issue by africalimedrop** [Dwarf-Fortress-13/Dwarf-Fortress-13#135]
Where do I get whitelisted/unbanned?

Just to make sure I've found the right people, I was just playing on 164.132.200.138:1997 before getting banned for not being on a whitelist.

**Comment by BartDrown** [comment]
You are not banned, server test is finished for now.
Please refer to discord in the following link:
https://discord.gg/eqxyhxYx

**Comment by africalimedrop** [comment]
OK, well that's no use for me as I won't use Discord, but you may want to add that link to the pop-up players receive when trying to join to get ahead of questions like mine. All I got was

`Banned by host: 
Reason: You are not on the white list for this server`

Very much enjoyed the server, and wish you the best with it all.
